- title: Microsaccades and image fading during natural vision
  authors: Igor Kagan
` publisher: Journal of Neuroscience
  date: 2012-12-20
  link: https://www.jneurosci.org/content/32/27/9194/tab-e-letters#microsaccades-and-image-fading-during-natural-vision
  type: eLetter