- id: doi:10.7554/eLife.81641
  type: paper
  description: Social decision-making
  image: https://iiif.elifesciences.org/digests/81641%2Fdigest-81641.jpeg/full/617,/0/default.webp
  buttons:
    - type: article
      text: eLife Digest
      link: https://elifesciences.org/digests/81641/the-art-of-compromise
    - type: source
      text: code and data
      link: https://osf.io/f5u8z/
    - type: website
      link: https://www.primate-cognition.eu/en/research/social-cognition-platform-project.html
  tags:
    - social decision-making
    - collaboration

  